name: Docker  

on:  
  push:  
    branches: [ main ]  

env:  
  REGISTRY: registry.cn-hangzhou.aliyuncs.com  
  MM_NOTIFY_URL: "${{ secrets.MM_NOTIFY_URL }}"  

jobs:  
  build:  
    name: Pull  
    runs-on: ubuntu-latest  
    steps:  
      - name: Setup Docker buildx  
        uses: docker/setup-buildx-action@v1

      - name: Check out code  
        uses: actions/checkout@v2  

      - name: Log in to Aliyun Registry  
        uses: docker/login-action@v1  
        with:  
          registry: ${{ env.REGISTRY }}  
          username: ${{ secrets.ALIYUN_REGISTRY_USER }}  
          password: ${{ secrets.ALIYUN_REGISTRY_PASSWORD }}  

      - name: Build and push image to ACR EE  
        run: |  
          sh pull.sh  
          data=$(cat trigger.txt)  

          if [ -n "$MM_NOTIFY_URL" ]; then  
            curl -H 'Content-Type: application/json' \
              -d "{\"msgtype\": \"text\",\"text\": {\"content\":\"同步成功 $data \"}}" \
              $MM_NOTIFY_URL  
          else  
            echo 'MM_NOTIFY_URL not set'  
          fi